kind: List
apiVersion: v1
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: filebeat-config
      labels:
        k8s-app: filebeat
        kubernetes.io/cluster-service: "true"
        app: filebeat-config
    data:
      filebeat.yml: |
        processors:
          - add_cloud_metadata:
        filebeat.modules:
        - module: system
        filebeat.inputs:
        - type: log
          paths:
            - /var/log/containers/*.log
          symlinks: true
          # json.message_key: log
          # json.keys_under_root: true
        output.kafka:
          hosts: ["kafka-service:9092"]
          topic: log
          required_acks: 1
        logging.level: info
  - apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: filebeat
      labels:
        k8s-app: filebeat
        kubernetes.io/cluster-service: "true"
    spec:
      selector:
        matchLabels:
          app: filebeat
      template:
        metadata:
          name: filebeat
          labels:
            app: filebeat
            k8s-app: filebeat
            kubernetes.io/cluster-service: "true"
        spec:
          containers:
            - image: docker.elastic.co/beats/filebeat:6.4.0
              name: filebeat
              args: ["-c", "/home/filebeat-config/filebeat.yml", "-e"]
              securityContext:
                runAsUser: 0
              volumeMounts:
                - name: filebeat-storage
                  mountPath: /var/log/containers
                - name: varlogpods
                  mountPath: /var/log/pods
                - name: varlibdockercontainers
                  mountPath: /var/lib/docker/containers
                - name: "filebeat-volume"
                  mountPath: "/home/filebeat-config"
          volumes:
            - name: filebeat-storage
              hostPath:
                path: /var/log/containers
            - name: varlogpods
              hostPath:
                path: /var/log/pods
            - name: varlibdockercontainers
              hostPath:
                path: /var/lib/docker/containers
            - name: filebeat-volume
              configMap:
                name: filebeat-config
