---
# Source logstash-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  type: ClusterIP
  ports:
    - name: filebeat
      port: 5044
      protocol: TCP
      targetPort: 5044
    - name: monitor
      port: 9600
      protocol: TCP
      targetPort: 9600
  selector:
    app: logstash
---
# Source logstash-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash
  labels:
    app: logstash
data:
  logstash.yml: |-
    http.host: "0.0.0.0"
    http.port: 9600
    log.level: info
    config.reload.automatic: true
  logstash.conf: |-
    input {
      kafka {
        bootstrap_servers => "kafka-svc:9092"
        topics => ["log" , "android"]
        codec => json
      }
    }

    filter {
      mutate {
        remove_field => ["beat","input","host","offset","prospector","@version"]
      }
    }

    output {
      elasticsearch {
        hosts => ["es-cn-nif1pv8pd000kfcfm.elasticsearch.aliyuncs.com:9200"]
        user => "elastic"
        password => "tq4jpF7+XLS8g"
        index => "log-%{+YYYY.MM.dd}"
        template_overwrite => true
        codec => line { format => "%{message}" }
      }
    }
---
# Source logstash-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.2.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: filebeat
              protocol: TCP
              containerPort: 5044
            - name: monitor
              protocol: TCP
              containerPort: 9600
          volumeMounts:
            - name: pipeline
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
            - name: config
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
      volumes:
        - name: pipeline
          configMap:
            name: logstash
            items:
              - key: logstash.conf
                path: logstash.conf
        - name: config
          configMap:
            name: logstash
            items:
              - key: logstash.yml
                path: logstash.yml
